In [20]:
import pandas as pd

In [2]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'C':[7,8]})

In [16]:
result=pd.concat([df1,df2],axis=0,join='inner',ignore_index=True)
result

   A
0  1
1  2
2  5
3  6

In [19]:
result=pd.concat([df1,df2],sort=True)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0